name: agri_nav
description: Rolnicza nawigacja GNSS — Flutter + C++
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
